### ISSUE TITLE
String literals

### ISSUE THREAD

**Issue by caracal7** [fwg/s-expression#10]
How to make the same behaviour for " and '. 
In my case I need " и ' to be parsed into String objects

**Comment by fwg** [comment]
Hi @caracal7,

I just published 3.1.0 to address this.

It is now possible to change the regular expressions the parser uses to find the start and end of things.

For an example how to change the parser to treat both `"` and `'` as string delimiters, see here:
https://github.com/fwg/s-expression/blob/d278321845b28423ec348f3ff3befcac36016cd9/test.js#L67

Cheers
